version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo-data:/data/db  # 🔥 comment this out to see non-persistent behavior

volumes:
  mongo-data:
